services:
  - type: web
    name: markitdown-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SELF_URL
        value: https://markitdown-service-zhmg.onrender.com
    autoDeploy: true
